name: Static analysis
on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

defaults:
  run:
    shell: bash

env:
  WORK_FLOW: ${{ github.workflow }}
  REF: ${{ github.ref }}
  VERSION: ${{ github.ref_name }}

concurrency:
  group: ${WORK_FLOW}-${REF}
  cancel-in-progress: true

jobs:
  first:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - run: echo $VERSION

  second:
    needs: [first]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 1
          sleep 10
          echo 2

  third:
    needs: [first]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo a
          sleep 10
          echo b

  fourth:
    needs: [second, third]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo last

  fifth:
    runs-on: ubuntu-latest
    steps:
      - run: echo flying
