name: Static analysis
on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash
env:
  WORK_FLOW: ${{ github.workflow }}
  REF: ${{ github.ref }}

concurrency:
  group: ${WORK_FLOW}-${REF}
  cancel-in-progress: true

jobs:
  sample:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "::group::Sample Log Group"
          sleep 10
          echo $WORK_FLOW
          echo $REF
          sleep 10
          echo ${{ github.workflow }}
          echo ${{ github.ref }}
          echo "::endgroup::"
