name: Static analysis
on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

defaults:
  run:
    shell: bash

env:
  WORK_FLOW: ${{ github.workflow }}
  REF: ${{ github.ref }}
  VERSION: ${{ github.ref_name }}

concurrency:
  group: ${WORK_FLOW}-${REF}
  cancel-in-progress: true

jobs:
  sample:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - run: echo $VERSION
