name: Static analysis
on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  WORK_FLOW: ${{ github.workflow }}
  REF: ${{ github.ref }}

concurrency:
  group: ${WORK_FLOW}-${REF}
  cancel-in-progress: true

jobs:
  sample:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: |
          echo "# Summary" >> "${GITHUB_STEp_SUMMARY}"
          echo "- [ ] hey" >> "${GITHUB_STEp_SUMMARY}"
