name: Sample-Action
on:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }} # workflowName-branchName
  cancel-in-progress: true # 同じbranchのworkflowが動いていたら、キャンセル
defaults:
  run:
    shell: bash # Errorを拾いやすくなる
env:
  ENVIRONMENT: dev # 変数の設定
jobs:
  first:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # 30分でタイムアウト. Default 360分
    steps:
      - run: echo $ENVIRONMENT
