name: Static analysis
on:
  push:
    branches:
      - 1-sample-issue

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" rhyds/actionlint:latest
