name: Sample-Action
run-name: run-name
on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
defaults:
  run:
    shell: bash # Errorを拾いやすくなる
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  first:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - run: echo ${{ github.workflow }}-${{ github.ref_name }}
