name: cross repo
on: push
env:
  TARGET_REPO: Taichi-iskw/repo-test
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - id: create
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          repositories: ${{ env.TARGET_REPO }}
      - uses: actions/checkout@v4
        with:
          repository: ${{github.repository_owner}}/${{env.TARGET_REPO}}
          path: ${{env.TARGET_REPO}}
          token: ${{ steps.create.outputs.token }}
      - run: |
          ls -l
          ls -l ${{env.TARGET_REPO}}
