name: Dispatch

on:
  workflow_dispatch: # 手動実行

jobs:
  docker-build-check:
    runs-on: ubuntu
    steps:
      - name: hello
        run: echo 'hello'
      # - name: Create Simple Dockerfile
      #   run: |
      #     echo 'FROM alpine' > Dockerfile
      #     echo 'CMD ["echo", "Hello from Docker!"]' >> Dockerfile

      # - name: Build Docker Image
      #   run: docker build -t test-image .

      # - name: Run Docker Image
      #   run: docker run --rm test-image
