name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: Hello
        description: A cheerful word
        required: true
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      JSON: ${{ fromJson(vars.JSON_SAMPLE) }}
      OBJ: ${{ toJson(vars.OBJ_SAMPLE)}}
    steps:
      - run: echo "${JSON}"
      - run: echo "${OBJ}"
