name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: Hello
        description: A cheerful word
        required: true
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ vars.USERNAME }}
      SAMPLE: ${{ vars.SAMPLE }}
      JSON: ${{ vars.JSON_SAMPLE }}
      OBJ: ${{ vars.OBJ_SAMPLE }}
    steps:
      - run: echo "${{toJson('${JSON}')}}"
      - run: echo "${{fromJson('${OBJ}')}}"
