name: Called Workflow
on:
  workflow_call:

jobs:
  simple-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print message
        run: echo "This is the called workflow!"
